// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ve.com.tracking.model;

import org.springframework.beans.factory.annotation.Configurable;
import ve.com.tracking.model.TrackingLogDataOnDemand;

privileged aspect TrackingLogDataOnDemand_Roo_Configurable {
    
    declare @type: TrackingLogDataOnDemand: @Configurable;
    
}
